### ISSUE TITLE
Enable encapsulation on your trunk ports

### ISSUE THREAD

**Issue by Techno11** [ejordan376/Cheesy-PLC#1]
On the field switch, encapsulation for dot1q is enabled on the port going to the driver station switches. Might wanna enable it on the DS switches too, it didn't work for me until I did. 

```switchport trunk encapsulation dot1q```

**Comment by FletcherS7** [comment]
The Allen Brady switches ONLY support dot1q encapsulation. So that command is not necessary and does not exist in this IOS image.
